version: '3.8'

services:
  # --- SERVICE 1: DATABASE (Si Drummer - Tetap Aman) ---
  db:
    image: postgres:15-alpine
    container_name: inventory_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mydonutgua123
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- SERVICE 2: MEJA RESEPSIONIS (Redis - BARU) ---
  redis_server:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6380:6379"
    restart: always

  # --- SERVICE 3: APLIKASI KASIR (Si Gitaris - Di-upgrade) ---
  app:
    build: .
    container_name: inventory_app_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db             # Tunggu DB siap
      - redis_server   # Tunggu Redis siap
    environment:
      # Koneksi Database Lama
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mydonutgua123
      - DB_NAME=inventory_db
      # Koneksi Redis Baru
      - REDIS_URL=redis://redis_container:6379

  # --- SERVICE 4: KOKI (Celery Worker - BARU) ---
  celery_worker:
    build: .
    container_name: celery_worker_container
    command: celery -A worker worker --loglevel=info
    depends_on:
      - db
      - redis_server
    environment:
      # Worker juga butuh akses ke DB dan Redis!
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mydonutgua123
      - DB_NAME=inventory_db
      - REDIS_URL=redis://redis_server:6379

  # --- SERVICE 5: MANAJER (Celery Beat - BARU) ---
  celery_beat:
    build: .
    container_name: celery_beat_container
    command: celery -A worker beat --loglevel=info
    depends_on:
      - db
      - redis_server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mydonutgua123
      - DB_NAME=inventory_db
      - REDIS_URL=redis://redis_server:6379

# --- DEFINISI VOLUME (GUDANG DATA) ---
volumes:
  postgres_data: