"""add_is_deleted_to_inventory

Revision ID: 4c82b8d93088
Revises: f139c2b0ac56
Create Date: 2026-05-08 23:17:54.924377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c82b8d93088'
down_revision: Union[str, None] = 'f139c2b0ac56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'is_deleted')
    # ### end Alembic commands ###