"""create_stock_logs_with_enum

Revision ID: f139c2b0ac56
Revises: 
Create Date: 2026-05-04 15:51:43.460834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f139c2b0ac56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('change_amount', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.Enum('IN', 'OUT', 'UPDATE', name='logtype'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_logs_id'), 'stock_logs', ['id'], unique=False)
    op.drop_index(op.f('idx_inventory_name'), table_name='inventory')
    op.drop_index(op.f('idx_inventory_name_trgm'), table_name='inventory', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_inventory_name'), 'inventory', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_name'), table_name='inventory')
    op.create_index(op.f('idx_inventory_name_trgm'), 'inventory', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_inventory_name'), 'inventory', ['name'], unique=False)
    op.drop_index(op.f('ix_stock_logs_id'), table_name='stock_logs')
    op.drop_table('stock_logs')
    # ### end Alembic commands ###