name: Inventory CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  # --- TUGAS 1: TESTING ---
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest

  # --- TUGAS 2: DEPLOYMENT (Baru!) ---
  deploy:
    name: Deploy to Render
    needs: test # <--- INI KUNCINYA! Jangan jalan kalau 'test' belum selesai/sukses.
    runs-on: ubuntu-latest
    
    # Syarat: Hanya jalan kalau push ke branch utama (bukan pull request)
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Render Deployment
      # Kita pakai curl (alat kirim request) untuk menembak Deploy Hook
      run: |
        curl "${{ secrets.RENDER_DEPLOY_HOOK }}"


#Catatan keras, pelajri bagian ci yaml di CI/CD harus paham betulllll!!!!