name: Inventory CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Kita fokus ke main saja
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    # Kita beri variabel palsu agar aplikasi tidak crash saat di-import
    env:
      DATABASE_URL: sqlite:///./test.db
      SECRET_KEY: testing_secret_key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx # Jaga-jaga jika belum ada di requirements.txt

    - name: Run Tests
      run: |
        pytest test/ # Sebutkan nama foldernya secara spesifik

  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Trigger Render Deployment
      run: |
        curl "${{ secrets.RENDER_DEPLOY_HOOK }}"