name: CI/CD Pipline - Build Docker Image

#robot bekerja setiap kali kode di push ke branch main atau master
on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # cloning code to the github comp
      - name: Checkout Code
        uses: actions/checkout@v3
    #prepare dock mach. at github
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    #Uji coba merakit peti kemas (Pastikan Dockerfile-mu valid)
      - name: Build Docker Image (Test)
        run: |
          echo "Merakit kapal kargo API di cloud.."
          docker build -t latif-warehouse-api: latest.
          echo "Perakitan sukses tanpa error!"